"""Check or repeat the selected field-water calibration in a separate run."""
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
import argparse
import hashlib
import json
import shutil
import subprocess
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'model/current_results/calibration'
DRIVERS = Path(__file__).resolve().parent / 'calibration_source'
sys.dont_write_bytecode = True


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--stage', choices=['check', 'fit'], default='check')
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--workers', type=int, default=4, help='Workers for objective checks; original optimizer uses four')
    args = parser.parse_args()
    if args.workers < 1:
        raise ValueError('Workers must be positive')
    output = args.output.resolve()
    if output == SOURCE or SOURCE in output.parents:
        raise ValueError('Preserve the completed calibration archive')
    if output.exists() and any(output.iterdir()):
        raise FileExistsError('Choose a new or empty output directory')
    manifest = json.loads((DRIVERS / 'source_manifest.json').read_text())
    for name, digest in manifest['original_files_sha256'].items():
        if sha(DRIVERS / name) != digest:
            raise AssertionError('Calibration source changed: ' + name)
    output.mkdir(parents=True, exist_ok=True)
    for name in ['data', 'source_snapshots']:
        shutil.copytree(SOURCE / name, output / name, ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
    for kind in ['field', 'station', 'reference']:
        shutil.copytree(SOURCE / 'inputs' / kind, output / 'inputs' / kind)
    shutil.copytree(DRIVERS, output / 'analysis_source')
    (output / 'parameters/candidates').mkdir(parents=True)
    (output / 'verification').mkdir()
    # These tables are regenerated by the optimizer, rather than sealed inputs.
    generated = {'data/used_new_water_field_wheat.csv', 'data/used_new_water_field_maize.csv'}
    inputs = [dict(snapshot=p.relative_to(output).as_posix(), sha256=sha(p))
              for p in sorted(output.rglob('*')) if p.is_file() and p.relative_to(output).as_posix() not in generated]
    (output / 'verification/input_manifest.json').write_text(json.dumps(inputs, indent=2) + '\n')
    sys.path.insert(0, str(output / 'analysis_source'))
    import field_water_fit as fit
    frozen = json.loads((SOURCE / 'parameters/frozen_model.json').read_text())['candidates']['management_refit']
    checks = []
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        for crop in ['wheat', 'maize']:
            field, payloads, *_ = fit.field_data(crop)
            names = fit.legacy.specification(crop)[0]
            indices = [names.index(n) for n in fit.WATER_NAMES]
            card = frozen[crop]
            vector = np.asarray(card['vector'])[indices]
            residual = fit.residuals(vector, crop, pool)
            data_loss = float(residual[:-8] @ residual[:-8])
            objective_loss = float(residual @ residual)
            if not np.isclose(data_loss, card['calibration_data_loss'], rtol=0, atol=1e-10):
                raise AssertionError('Published calibration data loss differs: ' + crop)
            if not np.isclose(objective_loss, card['objective_loss'], rtol=0, atol=1e-10):
                raise AssertionError('Published calibration objective differs: ' + crop)
            checks.append(dict(crop=crop, field_cases=len(payloads), target_records=len(field),
                               calibration_years=sorted(field.harvest_year.unique().astype(int).tolist()),
                               calibration_data_loss=data_loss, objective_loss=objective_loss,
                               testing_used=False, station_records_in_water_objective=0,
                               published_objective_matches=True))
            print(crop, 'calibration objective reproduced:', objective_loss, flush=True)
    if args.stage == 'fit':
        for crop in ['wheat', 'maize']:
            log = output / 'verification' / (crop + '_optimizer.log')
            with log.open('w') as stream:
                subprocess.run([sys.executable, '-B', str(output / 'analysis_source/field_water_fit.py'),
                                '--crop', crop], stdout=stream, stderr=subprocess.STDOUT, check=True)
            candidate = json.loads((output / 'parameters/candidates' / (crop + '_corrected_matric.json')).read_text())
            if not candidate['success'] or candidate['testing_used']:
                raise AssertionError('Calibration failed: ' + crop)
            checks[[c['crop'] for c in checks].index(crop)]['optimizer'] = {
                'converged': True,
                'maximum_vector_difference': float(np.max(np.abs(np.asarray(candidate['vector']) - frozen[crop]['vector']))),
                'calibration_data_loss_difference': candidate['calibration_data_loss'] - frozen[crop]['calibration_data_loss'],
            }
    receipt = dict(all_checks_passed=True, stage=args.stage, checks=checks,
                   original_calibration_sources_exact=True, external_checkout_required=False,
                   inherited_multisite_growth_parameters_fixed=True,
                   completed_utc=datetime.now(timezone.utc).isoformat(), driver_sha256=sha(__file__))
    (output / 'verification/calibration_objective.json').write_text(json.dumps(receipt, indent=2) + '\n')


if __name__ == '__main__':
    main()
